before_install:
  - "sudo apt-get install xclip xsel --no-install-recommends --yes"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby
notifications:
  recipients:
    - jordon@envygeeks.com
branches:
  only:
    - master
