before_install:
  - "sudo apt-get install xclip xsel --no-install-recommends --yes"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
rvm:
  - 2.0
  - 2.1
  - 2.2
notifications:
  recipients:
    - jordon@envygeeks.io
branches:
  only:
    - master
