before_install:
  - "sudo apt-get install xclip xsel --no-install-recommends --yes"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
rvm:
  - rbx-19mode
  - 2.0.0
  - 1.9.3
  - jruby-19mode
notifications:
  recipients:
    - envygeeks@gmail.com
branches:
  only:
    - master
